"""empty message

Revision ID: e36129149c08
Revises: e37304ca1da6
Create Date: 2026-04-19 16:50:27.496942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36129149c08'
down_revision: Union[str, Sequence[str], None] = 'e37304ca1da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('rooms', sa.Column('name', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'rooms', ['uuid'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'name')
    op.drop_column('documents', 'name')
    # ### end Alembic commands ###
