"""empty message

Revision ID: e37304ca1da6
Revises: 
Create Date: 2026-04-17 12:31:01.094191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37304ca1da6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rooms',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('documents',
    sa.Column('room_uuid', sa.String(length=64), nullable=True),
    sa.Column('document_uuid', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['room_uuid'], ['rooms.uuid'], ),
    sa.PrimaryKeyConstraint('document_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
